### ISSUE TITLE
Issue 2: Add Multiplayer Support

### ISSUE THREAD

**Issue by Soyvor** [lovishprabhakar/TicTacToe-Hacktoberfest#6]
Title: Implement Multiplayer Mode
Description: Currently, the game supports only single-player mode. It would be great to add a multiplayer mode where two players can play against each other.

**Comment by lovishprabhakar** [comment]
@Soyvor will you be working on this issue after the completion of the previous one? Let me know so that if yes, I will pin this issue so that it doesn't get unassigned automatically.
