### ISSUE TITLE
Issue 3: Enhance User Interface

### ISSUE THREAD

**Issue by Soyvor** [lovishprabhakar/TicTacToe-Hacktoberfest#7]
Description: The current user interface is functional but could be improved for a better user experience. Let's focus on enhancing the UI, making it visually appealing, and ensuring it's responsive on different screen sizes.

**Comment by Soyvor** [comment]
> Hey Contributor! You can start working on the issue. Good luck! Please comment `/assign` to get this issue assigned to you. Don't forget to star the repository!

/assign

**Comment by lovishprabhakar** [comment]
@Soyvor the automation failed for this issue for some reason, so I've manually assigned the issue to you. Looking forward to your contribution, good luck!

**Comment by Soyvor** [comment]
submitted the pr

**Comment by lovishprabhakar** [comment]
Review left on the PR @Soyvor.
